# Generated by Django 5.0.4 on 2024-05-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_alter_buses_bus_no_alter_buses_bus_sitting_capacity'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='destination',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='route',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='route',
            name='source',
        ),
        migrations.AddField(
            model_name='route',
            name='buses',
            field=models.ManyToManyField(related_name='routes', to='buses.buses'),
        ),
    ]
