# Generated by Django 5.0.4 on 2024-05-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_rename_destination_route_name_remove_route_distance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='buses',
        ),
        migrations.RemoveField(
            model_name='route',
            name='name',
        ),
        migrations.AddField(
            model_name='route',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='route',
            name='end_location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='route_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='route_number',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='start_location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
