# Generated by Django 5.0.4 on 2024-05-17 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_alter_buses_bus_no_alter_buses_bus_sitting_capacity'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='license_number',
        ),
        migrations.AddField(
            model_name='driver',
            name='bus',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='buses.buses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='contact',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
