# Generated by Django 5.0.4 on 2024-05-22 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_alter_buses_bus_no_alter_buses_bus_sitting_capacity'),
        ('drivers', '0002_remove_driver_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='bus',
        ),
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='bus_assigned',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='buses.buses'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
