# Generated by Django 5.0.4 on 2024-05-04 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.IntegerField(max_length=3)),
                ('bus_reg_no', models.CharField(max_length=50)),
                ('bus_route', models.CharField(max_length=50)),
                ('bus_driver_name', models.CharField(max_length=50)),
                ('bus_driver_contact', models.CharField(max_length=50)),
                ('bus_incharge_name', models.CharField(max_length=50)),
                ('bus_incharge_contact', models.CharField(max_length=50)),
                ('bus_model', models.CharField(max_length=50)),
                ('bus_sitting_capacity', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
