# Generated by Django 5.0.4 on 2024-05-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_alter_buses_bus_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='bus_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='buses',
            name='bus_sitting_capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
