# Generated by Django 5.0.4 on 2024-05-17 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0003_alter_buses_bus_no_alter_buses_bus_sitting_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incharge', to='buses.buses')),
            ],
        ),
    ]
