# Generated by Django 5.0.4 on 2024-05-23 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_alter_buses_bus_no_alter_buses_bus_sitting_capacity'),
        ('incharges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incharge',
            name='bus',
        ),
        migrations.AddField(
            model_name='incharge',
            name='assigned_bus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incharge', to='buses.buses'),
        ),
        migrations.AddField(
            model_name='incharge',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incharge',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='incharge',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
